// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:boilerplate/models/user.dart' as prefix1;
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:mobx/src/api/annotations.dart' as prefix2;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'_UserBase',
            r'._UserBase',
            551,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 9],
            const <int>[10, 11, 12, 13, 14, 3, 4, 5, 6, 7, 8],
            const <int>[],
            1,
            {},
            {},
            {},
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'dart.core.Object with .Store',
            r'.dart.core.Object with .Store',
            583,
            1,
            const prefix0.JsonSerializable(),
            const <int>[],
            const <int>[10, 11, 12, 13, 14],
            const <int>[],
            -1,
            const {},
            const {},
            const {},
            -1,
            -1,
            const <int>[],
            const [],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'id', 32773, 0, const prefix0.JsonSerializable(),
            -1, 2, 2, const <int>[], const <Object>[prefix2.observable]),
        r.VariableMirrorImpl(
            r'userName',
            32773,
            0,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const <Object>[prefix2.observable]),
        r.VariableMirrorImpl(
            r'password',
            32773,
            0,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const <Object>[prefix2.observable]),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 3),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 0, 4),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 5),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 1, 6),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 2, 7),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 2, 8),
        r.MethodMirrorImpl(r'', 64, 0, -1, 0, 0, const <int>[], const <int>[],
            const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 4, 4, const <int>[],
            const <int>[3], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 3, 3, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            null,
            null,
            null,
            null,
            const <int>[],
            const <int>[4],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 2, 2, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'runtimeType',
            131075,
            null,
            -1,
            5,
            5,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'_id',
            32870,
            4,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_userName',
            32870,
            6,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_password',
            32870,
            8,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            16390,
            10,
            const prefix0.JsonSerializable(),
            null,
            null,
            null,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            12,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        const r.FakeType(r'._UserBase'),
        const r.FakeType(r'.dart.core.Object with .Store'),
        int,
        String,
        bool,
        Type,
        Invocation
      ],
      2,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'id': (dynamic instance) => instance.id,
        r'userName': (dynamic instance) => instance.userName,
        r'password': (dynamic instance) => instance.password
      },
      {
        r'id=': (dynamic instance, value) => instance.id = value,
        r'userName=': (dynamic instance, value) => instance.userName = value,
        r'password=': (dynamic instance, value) => instance.password = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
